from sqlalchemy import Column, Integer, String, Boolean, DateTime, Date, Numeric, ForeignKey, Text
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
from ..database import Base


class Company(Base):
    __tablename__ = "companies"
    id = Column(Integer, primary_key=True, index=True)
    company_code = Column(String(20), unique=True, nullable=False)
    short_name = Column(String(40))
    company_name = Column(String(200), nullable=False)
    company_type = Column(String(20), nullable=False)
    business_no = Column(String(20))
    resident_type = Column(String(20))
    resident_no = Column(String(20))
    ceo_name = Column(String(50))
    business_type = Column(String(40))
    business_item = Column(String(40))
    postal_code = Column(String(7))
    address_detail1 = Column(String(60))
    address_detail2 = Column(String(100))
    address = Column(Text)
    phone = Column(String(20))
    fax = Column(String(20))
    homepage = Column(String(100))
    email = Column(String(150))
    liquor_code = Column(String(20))
    liquor_name = Column(String(100))
    country_code = Column(String(20))
    project_code = Column(String(30))
    project_name = Column(String(100))
    company_category_code = Column(String(30))
    company_category_name = Column(String(100))
    company_grade_code = Column(String(30))
    company_grade_name = Column(String(100))
    collection_customer_code = Column(String(30))
    collection_customer_name = Column(String(100))
    region_code = Column(String(30))
    region_name = Column(String(100))
    external_data_code = Column(String(50))
    electronic_tax_invoice_yn = Column(String(1))
    single_report_customer_code = Column(String(30))
    single_report_customer_name = Column(String(100))
    tax_business_no = Column(String(20))
    multi_supplier_yn = Column(String(1))
    purpose_type = Column(String(30))
    transaction_start_date = Column(Date)
    use_yn = Column(String(1), default="Y")
    contract_start_date = Column(Date)
    contract_end_date = Column(Date)
    transaction_status = Column(String(20))
    discount_rate = Column(Numeric(8, 4))
    contract_amount = Column(Numeric(18, 2))
    use_expense_amount = Column(Numeric(18, 2))
    payment_terms = Column(String(100))
    limit_recovery_days = Column(Integer)
    payment_bank_code = Column(String(30))
    payment_bank_name = Column(String(100))
    payment_branch_name = Column(String(100))
    payment_account_no = Column(String(50))
    payment_account_holder = Column(String(50))
    slip_type_code = Column(String(30))
    slip_type_name = Column(String(100))
    tax_category_code = Column(String(30))
    tax_category_name = Column(String(100))
    payment_due_day = Column(Integer)
    manager_department_code = Column(String(30))
    manager_department_name = Column(String(100))
    manager_position = Column(String(50))
    manager_task = Column(String(100))
    manager_employee_code = Column(String(30))
    manager_employee_name = Column(String(100))
    manager_phone = Column(String(20))
    manager_extension = Column(String(20))
    manager_mobile = Column(String(20))
    manager_email = Column(String(150))
    manager_notes = Column(Text)
    receiver_postal_code = Column(String(7))
    receiver_address1 = Column(String(100))
    receiver_address2 = Column(String(100))
    receiver_phone = Column(String(20))
    receiver_fax = Column(String(20))
    receiver_notes = Column(Text)
    bank_name = Column(String(50))
    bank_account = Column(String(50))
    bank_holder = Column(String(50))
    receivables_note = Column(Text)
    credit_limit = Column(Numeric(18, 2), default=0)
    is_active = Column(Boolean, default=True)
    notes = Column(Text)
    created_by = Column(Integer, ForeignKey("users.id"))
    created_at = Column(DateTime, default=func.now())
    updated_at = Column(DateTime, default=func.now(), onupdate=func.now())


class Site(Base):
    __tablename__ = "sites"
    id = Column(Integer, primary_key=True, index=True)
    site_code = Column(String(20), unique=True, nullable=False)
    job_no = Column(String(20), unique=True)
    site_name = Column(String(200), nullable=False)
    client_id = Column(Integer, ForeignKey("companies.id"))
    contract_type = Column(String(20))
    site_manager_id = Column(Integer, ForeignKey("users.id"))
    start_date = Column(Date)
    end_date = Column(Date)
    status = Column(String(20), default="active")
    location = Column(Text)
    notes = Column(Text)
    created_by = Column(Integer, ForeignKey("users.id"))
    created_at = Column(DateTime, default=func.now())
    updated_at = Column(DateTime, default=func.now(), onupdate=func.now())

    client = relationship("Company", foreign_keys=[client_id])
    manager = relationship("User", foreign_keys=[site_manager_id])


class CostCode(Base):
    __tablename__ = "cost_codes"
    id = Column(Integer, primary_key=True, index=True)
    code = Column(String(30), unique=True, nullable=False)
    name = Column(String(100), nullable=False)
    parent_id = Column(Integer, ForeignKey("cost_codes.id"))
    level = Column(Integer, default=1)
    cost_type = Column(String(20))
    account_code = Column(String(20))
    is_active = Column(Boolean, default=True)
    created_at = Column(DateTime, default=func.now())

    parent = relationship("CostCode", remote_side="CostCode.id", back_populates="children")
    children = relationship("CostCode", back_populates="parent")


class AccountCode(Base):
    __tablename__ = "account_codes"
    id = Column(Integer, primary_key=True, index=True)
    code = Column(String(20), unique=True, nullable=False)
    name = Column(String(100), nullable=False)
    parent_id = Column(Integer, ForeignKey("account_codes.id"))
    account_type = Column(String(20))
    is_vat = Column(Boolean, default=False)
    is_active = Column(Boolean, default=True)
    created_at = Column(DateTime, default=func.now())

    parent = relationship("AccountCode", remote_side="AccountCode.id")


class Material(Base):
    __tablename__ = "materials"
    id = Column(Integer, primary_key=True, index=True)
    material_code = Column(String(30), unique=True, nullable=False)
    material_name = Column(String(200), nullable=False)
    spec = Column(String(200))
    unit = Column(String(20))
    management_unit = Column(String(20))
    conversion_factor = Column(Numeric(18, 6), default=1)
    material_type = Column(String(20))
    procurement_type = Column(String(20))
    item_group_code = Column(String(30))
    item_group_name = Column(String(100))
    lot_use_yn = Column(String(1), default="N")
    inspection_type = Column(String(20))
    lot_quantity = Column(Numeric(18, 2), default=0)
    drawing_no = Column(String(50))
    hs_code = Column(String(30))
    width_value = Column(Numeric(18, 6), default=0)
    width_unit = Column(String(20))
    height_value = Column(Numeric(18, 6), default=0)
    height_unit = Column(String(20))
    depth_value = Column(Numeric(18, 6), default=0)
    depth_unit = Column(String(20))
    weight_value = Column(Numeric(18, 6), default=0)
    weight_unit = Column(String(20))
    area_value = Column(Numeric(18, 6), default=0)
    area_unit = Column(String(20))
    set_item_yn = Column(String(1), default="N")
    use_yn = Column(String(1), default="Y")
    batch_quantity = Column(Numeric(18, 2), default=0)
    barcode = Column(String(100))
    material_quality = Column(String(100))
    length_value = Column(Numeric(18, 6), default=0)
    length_unit = Column(String(20))
    density_value = Column(Numeric(18, 6), default=0)
    tax_type = Column(String(20))
    web_order_yn = Column(String(1))
    order_notes = Column(Text)
    cost_code_id = Column(Integer, ForeignKey("cost_codes.id"))
    standard_price = Column(Numeric(18, 2), default=0)
    is_active = Column(Boolean, default=True)
    notes = Column(Text)
    created_at = Column(DateTime, default=func.now())
    updated_at = Column(DateTime, default=func.now(), onupdate=func.now())

    cost_code = relationship("CostCode")


class UnitPrice(Base):
    __tablename__ = "unit_prices"
    id = Column(Integer, primary_key=True, index=True)
    material_id = Column(Integer, ForeignKey("materials.id"))
    vendor_id = Column(Integer, ForeignKey("companies.id"))
    price = Column(Numeric(18, 2), nullable=False)
    unit = Column(String(20))
    apply_year = Column(Integer, nullable=False)
    apply_from = Column(Date)
    apply_to = Column(Date)
    price_type = Column(String(20), default="standard")
    notes = Column(Text)
    created_by = Column(Integer, ForeignKey("users.id"))
    created_at = Column(DateTime, default=func.now())

    material = relationship("Material")
    vendor = relationship("Company")


class Employee(Base):
    __tablename__ = "employees"
    id = Column(Integer, primary_key=True, index=True)
    emp_code = Column(String(20), unique=True, nullable=False)
    name = Column(String(50), nullable=False)
    department_id = Column(Integer, ForeignKey("departments.id"))
    department_name = Column(String(100))
    position = Column(String(50))
    job_title = Column(String(50))
    task = Column(String(100))
    emp_type = Column(String(20), default="regular")
    hire_date = Column(Date)
    resign_date = Column(Date)
    birth_date = Column(Date)
    wedding_anniversary = Column(Date)
    phone = Column(String(20))
    email = Column(String(150))
    home_address = Column(String(200))
    corporate_card_no = Column(String(50))
    bank_name = Column(String(50))
    bank_account = Column(String(50))
    daily_wage = Column(Numeric(12, 2), default=0)
    monthly_salary = Column(Numeric(12, 2), default=0)
    is_active = Column(Boolean, default=True)
    created_at = Column(DateTime, default=func.now())
    updated_at = Column(DateTime, default=func.now(), onupdate=func.now())

    department = relationship("Department")


class OverheadRate(Base):
    __tablename__ = "overhead_rates"
    id = Column(Integer, primary_key=True, index=True)
    rate_year = Column(Integer, nullable=False)
    labor_rate = Column(Numeric(8, 4))
    overhead_rate = Column(Numeric(8, 4))
    profit_rate = Column(Numeric(8, 4))
    notes = Column(Text)
    created_by = Column(Integer, ForeignKey("users.id"))
    created_at = Column(DateTime, default=func.now())
