"""Create initial PostgreSQL schema baseline

Revision ID: 20260608_0001
Revises:
Create Date: 2026-06-08 10:05:22
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "20260608_0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('account_type', sa.String(length=20), nullable=True),
    sa.Column('is_vat', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['account_codes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_account_codes_id'), 'account_codes', ['id'], unique=False)
    op.create_table('cost_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('cost_type', sa.String(length=20), nullable=True),
    sa.Column('account_code', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['cost_codes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_cost_codes_id'), 'cost_codes', ['id'], unique=False)
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_departments_id'), 'departments', ['id'], unique=False)
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emp_code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.String(length=50), nullable=True),
    sa.Column('emp_type', sa.String(length=20), nullable=True),
    sa.Column('hire_date', sa.Date(), nullable=True),
    sa.Column('resign_date', sa.Date(), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('bank_name', sa.String(length=50), nullable=True),
    sa.Column('bank_account', sa.String(length=50), nullable=True),
    sa.Column('daily_wage', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('monthly_salary', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('emp_code')
    )
    op.create_index(op.f('ix_employees_id'), 'employees', ['id'], unique=False)
    op.create_table('materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_code', sa.String(length=30), nullable=False),
    sa.Column('material_name', sa.String(length=200), nullable=False),
    sa.Column('spec', sa.String(length=200), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('management_unit', sa.String(length=20), nullable=True),
    sa.Column('conversion_factor', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('material_type', sa.String(length=20), nullable=True),
    sa.Column('procurement_type', sa.String(length=20), nullable=True),
    sa.Column('item_group_code', sa.String(length=30), nullable=True),
    sa.Column('item_group_name', sa.String(length=100), nullable=True),
    sa.Column('lot_use_yn', sa.String(length=1), nullable=True),
    sa.Column('inspection_type', sa.String(length=20), nullable=True),
    sa.Column('lot_quantity', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('drawing_no', sa.String(length=50), nullable=True),
    sa.Column('hs_code', sa.String(length=30), nullable=True),
    sa.Column('width_value', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('width_unit', sa.String(length=20), nullable=True),
    sa.Column('height_value', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('height_unit', sa.String(length=20), nullable=True),
    sa.Column('depth_value', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('depth_unit', sa.String(length=20), nullable=True),
    sa.Column('weight_value', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('weight_unit', sa.String(length=20), nullable=True),
    sa.Column('area_value', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('area_unit', sa.String(length=20), nullable=True),
    sa.Column('set_item_yn', sa.String(length=1), nullable=True),
    sa.Column('use_yn', sa.String(length=1), nullable=True),
    sa.Column('batch_quantity', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('barcode', sa.String(length=100), nullable=True),
    sa.Column('material_quality', sa.String(length=100), nullable=True),
    sa.Column('length_value', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('length_unit', sa.String(length=20), nullable=True),
    sa.Column('density_value', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('tax_type', sa.String(length=20), nullable=True),
    sa.Column('web_order_yn', sa.String(length=1), nullable=True),
    sa.Column('order_notes', sa.Text(), nullable=True),
    sa.Column('cost_code_id', sa.Integer(), nullable=True),
    sa.Column('standard_price', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cost_code_id'], ['cost_codes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('material_code')
    )
    op.create_index(op.f('ix_materials_id'), 'materials', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.String(length=50), nullable=True),
    sa.Column('role', sa.String(length=30), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=True),
    sa.Column('record_id', sa.String(length=50), nullable=True),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_code', sa.String(length=20), nullable=False),
    sa.Column('short_name', sa.String(length=40), nullable=True),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('company_type', sa.String(length=20), nullable=False),
    sa.Column('business_no', sa.String(length=20), nullable=True),
    sa.Column('resident_type', sa.String(length=20), nullable=True),
    sa.Column('resident_no', sa.String(length=20), nullable=True),
    sa.Column('ceo_name', sa.String(length=50), nullable=True),
    sa.Column('business_type', sa.String(length=40), nullable=True),
    sa.Column('business_item', sa.String(length=40), nullable=True),
    sa.Column('postal_code', sa.String(length=7), nullable=True),
    sa.Column('address_detail1', sa.String(length=60), nullable=True),
    sa.Column('address_detail2', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('fax', sa.String(length=20), nullable=True),
    sa.Column('homepage', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('liquor_code', sa.String(length=20), nullable=True),
    sa.Column('liquor_name', sa.String(length=100), nullable=True),
    sa.Column('country_code', sa.String(length=20), nullable=True),
    sa.Column('project_code', sa.String(length=30), nullable=True),
    sa.Column('project_name', sa.String(length=100), nullable=True),
    sa.Column('company_category_code', sa.String(length=30), nullable=True),
    sa.Column('company_category_name', sa.String(length=100), nullable=True),
    sa.Column('company_grade_code', sa.String(length=30), nullable=True),
    sa.Column('company_grade_name', sa.String(length=100), nullable=True),
    sa.Column('collection_customer_code', sa.String(length=30), nullable=True),
    sa.Column('collection_customer_name', sa.String(length=100), nullable=True),
    sa.Column('region_code', sa.String(length=30), nullable=True),
    sa.Column('region_name', sa.String(length=100), nullable=True),
    sa.Column('external_data_code', sa.String(length=50), nullable=True),
    sa.Column('electronic_tax_invoice_yn', sa.String(length=1), nullable=True),
    sa.Column('single_report_customer_code', sa.String(length=30), nullable=True),
    sa.Column('single_report_customer_name', sa.String(length=100), nullable=True),
    sa.Column('tax_business_no', sa.String(length=20), nullable=True),
    sa.Column('multi_supplier_yn', sa.String(length=1), nullable=True),
    sa.Column('purpose_type', sa.String(length=30), nullable=True),
    sa.Column('transaction_start_date', sa.Date(), nullable=True),
    sa.Column('use_yn', sa.String(length=1), nullable=True),
    sa.Column('contract_start_date', sa.Date(), nullable=True),
    sa.Column('contract_end_date', sa.Date(), nullable=True),
    sa.Column('transaction_status', sa.String(length=20), nullable=True),
    sa.Column('discount_rate', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('contract_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('use_expense_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('payment_terms', sa.String(length=100), nullable=True),
    sa.Column('limit_recovery_days', sa.Integer(), nullable=True),
    sa.Column('payment_bank_code', sa.String(length=30), nullable=True),
    sa.Column('payment_bank_name', sa.String(length=100), nullable=True),
    sa.Column('payment_branch_name', sa.String(length=100), nullable=True),
    sa.Column('payment_account_no', sa.String(length=50), nullable=True),
    sa.Column('payment_account_holder', sa.String(length=50), nullable=True),
    sa.Column('slip_type_code', sa.String(length=30), nullable=True),
    sa.Column('slip_type_name', sa.String(length=100), nullable=True),
    sa.Column('tax_category_code', sa.String(length=30), nullable=True),
    sa.Column('tax_category_name', sa.String(length=100), nullable=True),
    sa.Column('payment_due_day', sa.Integer(), nullable=True),
    sa.Column('manager_department_code', sa.String(length=30), nullable=True),
    sa.Column('manager_department_name', sa.String(length=100), nullable=True),
    sa.Column('manager_position', sa.String(length=50), nullable=True),
    sa.Column('manager_task', sa.String(length=100), nullable=True),
    sa.Column('manager_employee_code', sa.String(length=30), nullable=True),
    sa.Column('manager_employee_name', sa.String(length=100), nullable=True),
    sa.Column('manager_phone', sa.String(length=20), nullable=True),
    sa.Column('manager_extension', sa.String(length=20), nullable=True),
    sa.Column('manager_mobile', sa.String(length=20), nullable=True),
    sa.Column('manager_email', sa.String(length=150), nullable=True),
    sa.Column('manager_notes', sa.Text(), nullable=True),
    sa.Column('receiver_postal_code', sa.String(length=7), nullable=True),
    sa.Column('receiver_address1', sa.String(length=100), nullable=True),
    sa.Column('receiver_address2', sa.String(length=100), nullable=True),
    sa.Column('receiver_phone', sa.String(length=20), nullable=True),
    sa.Column('receiver_fax', sa.String(length=20), nullable=True),
    sa.Column('receiver_notes', sa.Text(), nullable=True),
    sa.Column('bank_name', sa.String(length=50), nullable=True),
    sa.Column('bank_account', sa.String(length=50), nullable=True),
    sa.Column('bank_holder', sa.String(length=50), nullable=True),
    sa.Column('receivables_note', sa.Text(), nullable=True),
    sa.Column('credit_limit', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_code')
    )
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_table('dept_budgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('budget_year', sa.Integer(), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('q1', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('q2', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('q3', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('q4', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('budget_year', 'department', 'category')
    )
    op.create_index(op.f('ix_dept_budgets_id'), 'dept_budgets', ['id'], unique=False)
    op.create_table('fund_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_year', sa.Integer(), nullable=False),
    sa.Column('plan_month', sa.Integer(), nullable=False),
    sa.Column('planned_income', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('planned_expense', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('planned_balance', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('actual_income', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('actual_expense', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('actual_balance', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fund_plans_id'), 'fund_plans', ['id'], unique=False)
    op.create_table('overhead_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rate_year', sa.Integer(), nullable=False),
    sa.Column('labor_rate', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('overhead_rate', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('profit_rate', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_overhead_rates_id'), 'overhead_rates', ['id'], unique=False)
    op.create_table('period_closings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('close_year', sa.Integer(), nullable=False),
    sa.Column('close_month', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('closed_by', sa.Integer(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['closed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_period_closings_id'), 'period_closings', ['id'], unique=False)
    op.create_table('timesheets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('week_end', sa.Date(), nullable=False),
    sa.Column('total_hours', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('reject_reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timesheets_id'), 'timesheets', ['id'], unique=False)
    op.create_table('user_registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('position', sa.String(length=50), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_registrations_id'), 'user_registrations', ['id'], unique=False)
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plate_no', sa.String(length=20), nullable=False),
    sa.Column('vehicle_type', sa.String(length=50), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('model_year', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(length=30), nullable=True),
    sa.Column('purpose', sa.String(length=30), nullable=True),
    sa.Column('fuel_type', sa.String(length=20), nullable=True),
    sa.Column('manager_name', sa.String(length=100), nullable=True),
    sa.Column('insurance_exp', sa.Date(), nullable=True),
    sa.Column('inspect_exp', sa.Date(), nullable=True),
    sa.Column('current_km', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plate_no')
    )
    op.create_index(op.f('ix_vehicles_id'), 'vehicles', ['id'], unique=False)
    op.create_table('design_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(length=300), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('requester_name', sa.String(length=100), nullable=True),
    sa.Column('order_company_id', sa.Integer(), nullable=True),
    sa.Column('construction_company_id', sa.Integer(), nullable=True),
    sa.Column('partner_company_id', sa.Integer(), nullable=True),
    sa.Column('request_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['construction_company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['partner_company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_design_requests_id'), 'design_requests', ['id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_no', sa.String(length=30), nullable=True),
    sa.Column('project_name', sa.String(length=300), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('client_name', sa.String(length=200), nullable=True),
    sa.Column('contract_form', sa.String(length=20), nullable=True),
    sa.Column('contract_type', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('contract_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('contract_rate', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('contract_start', sa.Date(), nullable=True),
    sa.Column('contract_end', sa.Date(), nullable=True),
    sa.Column('construct_start', sa.Date(), nullable=True),
    sa.Column('construct_end', sa.Date(), nullable=True),
    sa.Column('pm_name', sa.String(length=100), nullable=True),
    sa.Column('pm_dept', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_table('sales_pipelines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pipeline_name', sa.String(length=200), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('expected_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('probability', sa.Integer(), nullable=True),
    sa.Column('weighted_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('expected_date', sa.Date(), nullable=True),
    sa.Column('sales_manager_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sales_manager_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_pipelines_id'), 'sales_pipelines', ['id'], unique=False)
    op.create_table('sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_code', sa.String(length=20), nullable=False),
    sa.Column('job_no', sa.String(length=20), nullable=True),
    sa.Column('site_name', sa.String(length=200), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('contract_type', sa.String(length=20), nullable=True),
    sa.Column('site_manager_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['site_manager_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_no'),
    sa.UniqueConstraint('site_code')
    )
    op.create_index(op.f('ix_sites_id'), 'sites', ['id'], unique=False)
    op.create_table('unit_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('apply_year', sa.Integer(), nullable=False),
    sa.Column('apply_from', sa.Date(), nullable=True),
    sa.Column('apply_to', sa.Date(), nullable=True),
    sa.Column('price_type', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unit_prices_id'), 'unit_prices', ['id'], unique=False)
    op.create_table('accounts_payable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('ref_type', sa.String(length=50), nullable=True),
    sa.Column('ref_id', sa.Integer(), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('invoice_no', sa.String(length=50), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('paid_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('outstanding_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_payable_id'), 'accounts_payable', ['id'], unique=False)
    op.create_table('ap_bills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bill_no', sa.String(length=30), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('vendor_name', sa.String(length=200), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('bill_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('vat_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('bill_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ap_bills_id'), 'ap_bills', ['id'], unique=False)
    op.create_table('cost_inputs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('cost_code_id', sa.Integer(), nullable=True),
    sa.Column('cost_type', sa.String(length=20), nullable=False),
    sa.Column('input_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('ref_type', sa.String(length=50), nullable=True),
    sa.Column('ref_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cost_code_id'], ['cost_codes.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cost_inputs_id'), 'cost_inputs', ['id'], unique=False)
    op.create_table('estimates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estimate_no', sa.String(length=30), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('estimate_type', sa.String(length=20), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('labor_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('material_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('subcontract_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('expense_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('overhead_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('profit_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('estimated_by', sa.Integer(), nullable=True),
    sa.Column('estimate_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['estimated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('estimate_no')
    )
    op.create_index(op.f('ix_estimates_id'), 'estimates', ['id'], unique=False)
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expense_no', sa.String(length=30), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('cost_code_id', sa.Integer(), nullable=True),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('expense_type', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('vat_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('receipt_no', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('requested_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['cost_code_id'], ['cost_codes.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('expense_no')
    )
    op.create_index(op.f('ix_expenses_id'), 'expenses', ['id'], unique=False)
    op.create_table('inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('material_id', sa.Integer(), nullable=True),
    sa.Column('current_qty', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('reserved_qty', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('available_qty', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('avg_unit_price', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_id'), 'inventory', ['id'], unique=False)
    op.create_table('inventory_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('material_id', sa.Integer(), nullable=True),
    sa.Column('transaction_type', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('ref_type', sa.String(length=50), nullable=True),
    sa.Column('ref_id', sa.Integer(), nullable=True),
    sa.Column('cost_code_id', sa.Integer(), nullable=True),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cost_code_id'], ['cost_codes.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_transactions_id'), 'inventory_transactions', ['id'], unique=False)
    op.create_table('journal_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_no', sa.String(length=30), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('entry_type', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('total_debit', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_credit', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('ref_type', sa.String(length=50), nullable=True),
    sa.Column('ref_id', sa.Integer(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entry_no')
    )
    op.create_index(op.f('ix_journal_entries_id'), 'journal_entries', ['id'], unique=False)
    op.create_table('labor_inputs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('cost_code_id', sa.Integer(), nullable=True),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('work_days', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('daily_wage', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('insurance_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('net_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cost_code_id'], ['cost_codes.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_labor_inputs_id'), 'labor_inputs', ['id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_no', sa.String(length=30), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('payment_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=20), nullable=True),
    sa.Column('bank_name', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_no')
    )
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_table('project_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('plan_year', sa.Integer(), nullable=False),
    sa.Column('plan_month', sa.Integer(), nullable=False),
    sa.Column('revenue_plan', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('material_plan', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('labor_plan', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('subcontract_plan', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('expense_plan', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'plan_year', 'plan_month')
    )
    op.create_index(op.f('ix_project_plans_id'), 'project_plans', ['id'], unique=False)
    op.create_table('purchase_contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_no', sa.String(length=30), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('vendor_name', sa.String(length=200), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('contract_name', sa.String(length=300), nullable=False),
    sa.Column('contract_type', sa.String(length=20), nullable=True),
    sa.Column('contract_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_contracts_id'), 'purchase_contracts', ['id'], unique=False)
    op.create_table('purchase_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_no', sa.String(length=30), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('request_type', sa.String(length=20), nullable=False),
    sa.Column('request_date', sa.Date(), nullable=False),
    sa.Column('required_date', sa.Date(), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('requested_by', sa.Integer(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_no')
    )
    op.create_index(op.f('ix_purchase_requests_id'), 'purchase_requests', ['id'], unique=False)
    op.create_table('release_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_no', sa.String(length=30), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('material_name', sa.String(length=200), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('request_date', sa.Date(), nullable=True),
    sa.Column('needed_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_release_requests_id'), 'release_requests', ['id'], unique=False)
    op.create_table('revenue_forecasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('forecast_year', sa.Integer(), nullable=False),
    sa.Column('forecast_month', sa.Integer(), nullable=False),
    sa.Column('forecast_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('actual_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('achievement_rate', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_revenue_forecasts_id'), 'revenue_forecasts', ['id'], unique=False)
    op.create_table('sales_bills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bill_no', sa.String(length=30), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('client_name', sa.String(length=200), nullable=True),
    sa.Column('bill_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('vat_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('bill_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('invoice_no', sa.String(length=50), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_bills_id'), 'sales_bills', ['id'], unique=False)
    op.create_table('subcontracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subcontract_no', sa.String(length=30), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('contract_name', sa.String(length=200), nullable=False),
    sa.Column('cost_code_id', sa.Integer(), nullable=True),
    sa.Column('contract_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('advance_payment', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('retention_rate', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('payment_terms', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cost_code_id'], ['cost_codes.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subcontract_no')
    )
    op.create_index(op.f('ix_subcontracts_id'), 'subcontracts', ['id'], unique=False)
    op.create_table('timesheet_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timesheet_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('project_name', sa.String(length=300), nullable=True),
    sa.Column('work_type', sa.String(length=50), nullable=True),
    sa.Column('mon_hours', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('tue_hours', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('wed_hours', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('thu_hours', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('fri_hours', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('sat_hours', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('sun_hours', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['timesheet_id'], ['timesheets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timesheet_entries_id'), 'timesheet_entries', ['id'], unique=False)
    op.create_table('vehicle_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('driver_name', sa.String(length=100), nullable=False),
    sa.Column('driver_dept', sa.String(length=100), nullable=True),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('depart_time', sa.String(length=5), nullable=True),
    sa.Column('arrive_time', sa.String(length=5), nullable=True),
    sa.Column('start_km', sa.Integer(), nullable=True),
    sa.Column('end_km', sa.Integer(), nullable=True),
    sa.Column('distance', sa.Integer(), nullable=True),
    sa.Column('departure', sa.String(length=200), nullable=True),
    sa.Column('destination', sa.String(length=200), nullable=True),
    sa.Column('purpose', sa.String(length=50), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('project_name', sa.String(length=300), nullable=True),
    sa.Column('fuel_amount', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('fuel_cost', sa.Integer(), nullable=True),
    sa.Column('toll_cost', sa.Integer(), nullable=True),
    sa.Column('parking_cost', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_logs_id'), 'vehicle_logs', ['id'], unique=False)
    op.create_table('contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_no', sa.String(length=30), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('estimate_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('contract_name', sa.String(length=300), nullable=False),
    sa.Column('contract_type', sa.String(length=20), nullable=False),
    sa.Column('revenue_type', sa.String(length=20), nullable=True),
    sa.Column('original_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('current_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('original_cost', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('current_cost', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('contract_date', sa.Date(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('sales_manager_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['estimate_id'], ['estimates.id'], ),
    sa.ForeignKeyConstraint(['sales_manager_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contract_no')
    )
    op.create_index(op.f('ix_contracts_id'), 'contracts', ['id'], unique=False)
    op.create_table('estimate_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estimate_id', sa.Integer(), nullable=True),
    sa.Column('cost_code_id', sa.Integer(), nullable=True),
    sa.Column('item_name', sa.String(length=200), nullable=False),
    sa.Column('spec', sa.String(length=200), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cost_code_id'], ['cost_codes.id'], ),
    sa.ForeignKeyConstraint(['estimate_id'], ['estimates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estimate_items_id'), 'estimate_items', ['id'], unique=False)
    op.create_table('journal_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=True),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('debit_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('credit_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('cost_code_id', sa.Integer(), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('tax_invoice_no', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account_codes.id'], ),
    sa.ForeignKeyConstraint(['cost_code_id'], ['cost_codes.id'], ),
    sa.ForeignKeyConstraint(['entry_id'], ['journal_entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journal_lines_id'), 'journal_lines', ['id'], unique=False)
    op.create_table('payment_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('payable_id', sa.Integer(), nullable=True),
    sa.Column('applied_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['payable_id'], ['accounts_payable.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_items_id'), 'payment_items', ['id'], unique=False)
    op.create_table('purchase_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_no', sa.String(length=30), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.Column('order_type', sa.String(length=20), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('delivery_date', sa.Date(), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('vat_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['purchase_requests.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_no')
    )
    op.create_index(op.f('ix_purchase_orders_id'), 'purchase_orders', ['id'], unique=False)
    op.create_table('purchase_request_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.Column('material_id', sa.Integer(), nullable=True),
    sa.Column('item_name', sa.String(length=200), nullable=False),
    sa.Column('spec', sa.String(length=200), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('cost_code_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cost_code_id'], ['cost_codes.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['purchase_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_request_items_id'), 'purchase_request_items', ['id'], unique=False)
    op.create_table('subcontract_billings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('billing_no', sa.String(length=30), nullable=False),
    sa.Column('subcontract_id', sa.Integer(), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('billing_seq', sa.Integer(), nullable=False),
    sa.Column('billing_date', sa.Date(), nullable=False),
    sa.Column('progress_rate', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('billing_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('vat_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('cumulative_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['subcontract_id'], ['subcontracts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('billing_no')
    )
    op.create_index(op.f('ix_subcontract_billings_id'), 'subcontract_billings', ['id'], unique=False)
    op.create_table('budgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('budget_name', sa.String(length=100), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budgets_id'), 'budgets', ['id'], unique=False)
    op.create_table('contract_changes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=True),
    sa.Column('change_no', sa.Integer(), nullable=False),
    sa.Column('change_date', sa.Date(), nullable=False),
    sa.Column('amount_before', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('amount_change', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('amount_after', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('cost_before', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('cost_change', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('cost_after', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('end_date_before', sa.Date(), nullable=True),
    sa.Column('end_date_after', sa.Date(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_changes_id'), 'contract_changes', ['id'], unique=False)
    op.create_table('progress_billings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('billing_no', sa.String(length=30), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('billing_seq', sa.Integer(), nullable=False),
    sa.Column('billing_date', sa.Date(), nullable=False),
    sa.Column('progress_rate', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('billing_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('vat_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('cumulative_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('invoice_no', sa.String(length=50), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('billing_no')
    )
    op.create_index(op.f('ix_progress_billings_id'), 'progress_billings', ['id'], unique=False)
    op.create_table('purchase_order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('material_id', sa.Integer(), nullable=True),
    sa.Column('item_name', sa.String(length=200), nullable=False),
    sa.Column('spec', sa.String(length=200), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('ordered_qty', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('received_qty', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('cost_code_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cost_code_id'], ['cost_codes.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['purchase_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_order_items_id'), 'purchase_order_items', ['id'], unique=False)
    op.create_table('receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receipt_no', sa.String(length=30), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('receipt_date', sa.Date(), nullable=False),
    sa.Column('invoice_no', sa.String(length=50), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('vat_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('inspector_id', sa.Integer(), nullable=True),
    sa.Column('inspected_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['inspector_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('receipt_no')
    )
    op.create_index(op.f('ix_receipts_id'), 'receipts', ['id'], unique=False)
    op.create_table('accounts_receivable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('billing_id', sa.Integer(), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('billing_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('collected_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('outstanding_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['billing_id'], ['progress_billings.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_receivable_id'), 'accounts_receivable', ['id'], unique=False)
    op.create_table('budget_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('budget_id', sa.Integer(), nullable=True),
    sa.Column('cost_code_id', sa.Integer(), nullable=True),
    sa.Column('cost_type', sa.String(length=20), nullable=True),
    sa.Column('item_name', sa.String(length=200), nullable=True),
    sa.Column('budgeted_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('execution_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('actual_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cost_code_id'], ['cost_codes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budget_items_id'), 'budget_items', ['id'], unique=False)
    op.create_table('collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collection_no', sa.String(length=30), nullable=False),
    sa.Column('billing_id', sa.Integer(), nullable=True),
    sa.Column('contract_id', sa.Integer(), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('collected_date', sa.Date(), nullable=False),
    sa.Column('collected_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('bank_name', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['billing_id'], ['progress_billings.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('collection_no')
    )
    op.create_index(op.f('ix_collections_id'), 'collections', ['id'], unique=False)
    op.create_table('receipt_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receipt_id', sa.Integer(), nullable=True),
    sa.Column('order_item_id', sa.Integer(), nullable=True),
    sa.Column('material_id', sa.Integer(), nullable=True),
    sa.Column('item_name', sa.String(length=200), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('received_qty', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('returned_qty', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('cost_code_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cost_code_id'], ['cost_codes.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['order_item_id'], ['purchase_order_items.id'], ),
    sa.ForeignKeyConstraint(['receipt_id'], ['receipts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receipt_items_id'), 'receipt_items', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_receipt_items_id'), table_name='receipt_items')
    op.drop_table('receipt_items')
    op.drop_index(op.f('ix_collections_id'), table_name='collections')
    op.drop_table('collections')
    op.drop_index(op.f('ix_budget_items_id'), table_name='budget_items')
    op.drop_table('budget_items')
    op.drop_index(op.f('ix_accounts_receivable_id'), table_name='accounts_receivable')
    op.drop_table('accounts_receivable')
    op.drop_index(op.f('ix_receipts_id'), table_name='receipts')
    op.drop_table('receipts')
    op.drop_index(op.f('ix_purchase_order_items_id'), table_name='purchase_order_items')
    op.drop_table('purchase_order_items')
    op.drop_index(op.f('ix_progress_billings_id'), table_name='progress_billings')
    op.drop_table('progress_billings')
    op.drop_index(op.f('ix_contract_changes_id'), table_name='contract_changes')
    op.drop_table('contract_changes')
    op.drop_index(op.f('ix_budgets_id'), table_name='budgets')
    op.drop_table('budgets')
    op.drop_index(op.f('ix_subcontract_billings_id'), table_name='subcontract_billings')
    op.drop_table('subcontract_billings')
    op.drop_index(op.f('ix_purchase_request_items_id'), table_name='purchase_request_items')
    op.drop_table('purchase_request_items')
    op.drop_index(op.f('ix_purchase_orders_id'), table_name='purchase_orders')
    op.drop_table('purchase_orders')
    op.drop_index(op.f('ix_payment_items_id'), table_name='payment_items')
    op.drop_table('payment_items')
    op.drop_index(op.f('ix_journal_lines_id'), table_name='journal_lines')
    op.drop_table('journal_lines')
    op.drop_index(op.f('ix_estimate_items_id'), table_name='estimate_items')
    op.drop_table('estimate_items')
    op.drop_index(op.f('ix_contracts_id'), table_name='contracts')
    op.drop_table('contracts')
    op.drop_index(op.f('ix_vehicle_logs_id'), table_name='vehicle_logs')
    op.drop_table('vehicle_logs')
    op.drop_index(op.f('ix_timesheet_entries_id'), table_name='timesheet_entries')
    op.drop_table('timesheet_entries')
    op.drop_index(op.f('ix_subcontracts_id'), table_name='subcontracts')
    op.drop_table('subcontracts')
    op.drop_index(op.f('ix_sales_bills_id'), table_name='sales_bills')
    op.drop_table('sales_bills')
    op.drop_index(op.f('ix_revenue_forecasts_id'), table_name='revenue_forecasts')
    op.drop_table('revenue_forecasts')
    op.drop_index(op.f('ix_release_requests_id'), table_name='release_requests')
    op.drop_table('release_requests')
    op.drop_index(op.f('ix_purchase_requests_id'), table_name='purchase_requests')
    op.drop_table('purchase_requests')
    op.drop_index(op.f('ix_purchase_contracts_id'), table_name='purchase_contracts')
    op.drop_table('purchase_contracts')
    op.drop_index(op.f('ix_project_plans_id'), table_name='project_plans')
    op.drop_table('project_plans')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_labor_inputs_id'), table_name='labor_inputs')
    op.drop_table('labor_inputs')
    op.drop_index(op.f('ix_journal_entries_id'), table_name='journal_entries')
    op.drop_table('journal_entries')
    op.drop_index(op.f('ix_inventory_transactions_id'), table_name='inventory_transactions')
    op.drop_table('inventory_transactions')
    op.drop_index(op.f('ix_inventory_id'), table_name='inventory')
    op.drop_table('inventory')
    op.drop_index(op.f('ix_expenses_id'), table_name='expenses')
    op.drop_table('expenses')
    op.drop_index(op.f('ix_estimates_id'), table_name='estimates')
    op.drop_table('estimates')
    op.drop_index(op.f('ix_cost_inputs_id'), table_name='cost_inputs')
    op.drop_table('cost_inputs')
    op.drop_index(op.f('ix_ap_bills_id'), table_name='ap_bills')
    op.drop_table('ap_bills')
    op.drop_index(op.f('ix_accounts_payable_id'), table_name='accounts_payable')
    op.drop_table('accounts_payable')
    op.drop_index(op.f('ix_unit_prices_id'), table_name='unit_prices')
    op.drop_table('unit_prices')
    op.drop_index(op.f('ix_sites_id'), table_name='sites')
    op.drop_table('sites')
    op.drop_index(op.f('ix_sales_pipelines_id'), table_name='sales_pipelines')
    op.drop_table('sales_pipelines')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_design_requests_id'), table_name='design_requests')
    op.drop_table('design_requests')
    op.drop_index(op.f('ix_vehicles_id'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_user_registrations_id'), table_name='user_registrations')
    op.drop_table('user_registrations')
    op.drop_index(op.f('ix_timesheets_id'), table_name='timesheets')
    op.drop_table('timesheets')
    op.drop_index(op.f('ix_period_closings_id'), table_name='period_closings')
    op.drop_table('period_closings')
    op.drop_index(op.f('ix_overhead_rates_id'), table_name='overhead_rates')
    op.drop_table('overhead_rates')
    op.drop_index(op.f('ix_fund_plans_id'), table_name='fund_plans')
    op.drop_table('fund_plans')
    op.drop_index(op.f('ix_dept_budgets_id'), table_name='dept_budgets')
    op.drop_table('dept_budgets')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_materials_id'), table_name='materials')
    op.drop_table('materials')
    op.drop_index(op.f('ix_employees_id'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_departments_id'), table_name='departments')
    op.drop_table('departments')
    op.drop_index(op.f('ix_cost_codes_id'), table_name='cost_codes')
    op.drop_table('cost_codes')
    op.drop_index(op.f('ix_account_codes_id'), table_name='account_codes')
    op.drop_table('account_codes')
    # ### end Alembic commands ###
